### ISSUE TITLE
PROMPT is added to counsel-term-history

### ISSUE THREAD

**Issue by JohnLunzer** [tautologyclub/counsel-term#1]
In this function:
```elisp
(defun counsel-term-history--initial-input-function ()
  "Check if term-prompt-regexp has been set and use it if so."
  (if (string= "" term-prompt-regexp)
      counsel-th-initial-input
    (concat counsel-th-initial-input (term-get-old-input-default))))
```
The culprit appears to be the call to ```(term-get-old-input-default)```. The effect is that whole prompt (in the case of a single line prompt) or the second line (in the case of multi-line prompt) gets picked up as input. To clarify a multi line prompt is a prompt ($PS1) which includes a ```\n``` character.

A quick look into term.el shows that `term-prompt-regexp` is integral to `term-get-old-input-default`.

When I set `term-prompt-regexp` to match the last few characters of my prompt `counsel-term-history` works as expected.

I don't mind setting this in my config file but would be nice if this was set automatically.

**Comment by JohnLunzer** [comment]
Almost as expected... when I press enter in the counsel selection the second line of my prompt gets wiped out when it places my selection on the prompt.

Maybe I'm doing it wrong, would love some advice.

**Comment by tautologyclub** [comment]
Sorry didnt see this...

Ehmm... yeah I dunno the reason for the prompt-regex is because my prompt has a \newline after the directory. So basically my solution was made to accomodate all 0.01% of us who has a non-standard prompt like this. To be honest I'm not sure what the question is, haha. Does it work fine after you set the prompt-regex?

**Comment by tautologyclub** [comment]
with a standard prompt, a decent prompt-regexp should be "$\\\ ". mine is "^$\\\ "

**Comment by JohnLunzer** [comment]
Haha, honestly I can't remember now either. Basically my prompt was getting picked up as previously typed input used to populate the term history function. Honestly I'm fine closing this because I haven't been using it much.
